	[project]
name = "cv-webcam-object-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy>=2.4.2",
    "opencv-python-headless>=4.10.0.84",
    "pyyaml>=6.0.3",
    "streamlit>=1.54.0",
    "streamlit-webrtc>=0.64.5",
    "ultralytics>=8.4.14",
]
